### PR TITLE
Update Teams.json

### PR DESCRIPTION
**Pull request by PandaxCSGO**

### CODE REVIEW

**Comment by OhhLoz** [comment]
Thank you!

**Comment by PandaxCSGO** [comment]
No Problem, Tomorrow i go add to many more team.

**Comment by OhhLoz** [comment]
I only added the most popular teams at the time. The problem is that teams with a space in their name such as NAVI/Natus Vincere mess up the .[teamname] command as there is currently no implementation to correct for it. Thats why there is an alternateteams.json file. Hopefully when I get around to supporting this fully I can fix this.

**Comment by PandaxCSGO** [comment]
Oh yes, i fix it tomorrow ( i have add 2 or 3 teams with space )

**Pull request merged**
